nome = str(input('Digite seu nome completo: ')).strip()
print('Analisando seu nome...')
print(f'Seu nome em maiúsculas é {nome.upper()}')
print(f'Seu nome em minúsculas é {nome.lower()}')
# nome_sem_espaco = nome.replace(' ', '')
print(f'Seu nome tem {(len(nome) - nome.count(' '))} letras')
nome_separado = nome.split()
print(f'Seu primeiro nome é {nome_separado[0]} e ele tem {len(nome_separado[0])} letras')